include:
  - path: ./docker-compose.yaml

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MINIO_ENDPOINT=http://minio:9000
      - MONGODB_HOST=mongodb
    depends_on:
      - minio
      - mongodb

networks:
  default:
    driver: bridge