version: '3.1'
services:
  postgresql:
    container_name: postgresql
    image: postgres:15.6-alpine
    ports:
      - "${port}:5432"
    environment:
      POSTGRES_USER: "${username}"
      POSTGRES_PASSWORD: "${password}"
    volumes:
      - ${volume}:/var/lib/postgresql/data